name: Check links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "15 07 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Set environment
        run: |
          while read line; do
          echo "$line" >> $GITHUB_ENV
          done < .github/workflows/.env
      ## Build website
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hugo \
            --minify \
            --baseURL "/"
      - name: Create search index
        run: npx -y pagefind --site public

        ## Check links
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.6.1
        with:
          fail: false 
          args: --exclude https://github.dev/cabforum/cabforum.org/ --exclude https://github.com/cabforum/cabforum.org/ --exclude https://wiki.cabforum.org  --exclude "^https://github\.com/[^/]+/[^/]+/compare" --exclude "^https://github\.com/[^/]+/[^/]+/blob" --exclude "^https://github\.com/[^/]+/[^/]+/tree" --base ./public --cache --max-cache-age 1d --no-progress ./public
          
      - name: Find Link Checker Issue
        id: link-checker-issue
        if: env.lychee_exit_code != 0
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            link checker
      
      ## Create/update issue
      - name: Create or update Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          issue-number: "${{ steps.link-checker-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          labels: link checker, automated issue
